# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0002_sheet_page_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='album',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='music',
            field=models.CharField(max_length=50),
        ),
    ]
